### PR TITLE
Curved connection

### PR DESCRIPTION
**Pull request by VladimirWrites**
It's a more natural way to animate connection between two circles. I used path that has a concave line at top and convex at the bottom.
Also, I did Gradle and Support library upgrade and incremented lib version to 0.0.9
I hope that I followed your coding standards :).

### CODE REVIEW

**Comment by wezley98** [comment]
+1

**Comment by VladimirWrites** [comment]
@GwonHyeok  Is there any specific reason to why are you not doing a merge on this pull request? Is there a something that I could improve?

**Comment by GwonHyeok** [comment]
@vlad1m1r990 
sorry for my belated reply

First of all, thank you for your interest in my project.
I want to this animation make as option

i want this option will be called **AnimationType**

ex )
**AnimationType** Attribute
* default
* curved
* etc...

thank you 😂😃😃 👍 💯

**Comment by VladimirWrites** [comment]
It's implemented as attribute now. Options are "line" and "curved" (can't be named "default"). I added Enum in StickySwitch.kt and am using enum in attrs.xml. If you had another way to solve this in mind write me and I will change it.

**Comment by GwonHyeok** [comment]
@vlad1m1r990 

Thank you. 
Now I try to merge your pull request, but your code has typo
if you fix this typo and update README.md , I will merge immediately!

StickySwitch.kt
1. line 348 -- } else if (animationType == AnimationType.CURVED) {**\\**

README.md
1. explain for animationType

🥇 👍

**Comment by VladimirWrites** [comment]
I had some problems doing merge with your changes, but I think everything should be fine now.
And sorry for typos, I was in a hurry :(.

**Pull request merged**
